<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login  Daftar</name>
   <tag></tag>
   <elementGuidId>8c209b81-25eb-4737-98b9-d900ef9ffa87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div[4]/header/div/div[3]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6627ee65-24ad-43bc-9793-11635dbedfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>708acfe0-1d71-49ad-a777-5b25a4ef2e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>fb1860c2-e124-4b4e-a95f-25ec2608319c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-variant</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d744df1a-9f8f-4e3e-9cdc-80e0e99b6151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ed96b6f4-3975-4104-9f68-8cb163531f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-square</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a55c74cb-d539-4ba2-877c-a69b1b7c68e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0da3fe1f-f27e-43f8-b746-37a4b0ca4ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__StyledButton-sc-1l0qx1m-2 ieGcCN</value>
      <webElementGuid>132de615-6f49-45dc-95f0-52ee1acd9f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login / Daftar</value>
      <webElementGuid>3244a5db-fa0a-4f4f-8ff3-297e38b15edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-sm Header___StyledMedia-y4d4ki-39 eRNBMj&quot;]/header[@class=&quot;Header___StyledHeader-y4d4ki-40 eCJwfa&quot;]/div[@class=&quot;Header___StyledDiv20-y4d4ki-41 iIUSWJ&quot;]/div[@class=&quot;Header___StyledDiv26-y4d4ki-47 kEQDlx&quot;]/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-lg&quot;]/button[@class=&quot;Button__StyledButton-sc-1l0qx1m-2 ieGcCN&quot;]</value>
      <webElementGuid>a71c2750-ba8a-4fa2-a881-52cbdc8e0d08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div[4]/header/div/div[3]/div[2]/button</value>
      <webElementGuid>3d8aa3f6-458c-4d28-a98d-44d4b7d05568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Cart'])[1]/following::button[1]</value>
      <webElementGuid>3ac78112-d49b-4f8e-b9f4-0405a1437b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xiaomi Gaming Monitor'])[1]/following::button[2]</value>
      <webElementGuid>d37e850a-a866-4355-aa13-45c0c72ae0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::button[1]</value>
      <webElementGuid>adb667e5-b8d6-417a-ac9c-589863ba344e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>49d3b180-11c7-42a4-abfb-c0fb9cd33dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Login / Daftar' or . = 'Login / Daftar')]</value>
      <webElementGuid>c0949312-0ee9-4fbb-b3f0-f10a25cffd21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
