<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_atau daftar dengan email_name</name>
   <tag></tag>
   <elementGuidId>fabe1834-3d1f-4f13-979e-4c13742b82b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa8c61bf-88e4-4495-ae47-7f1ae5fb9d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>0075f067-0315-4566-9632-a1263b650747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input___StyledInput-sc-1en4ex3-14 ezAWtV</value>
      <webElementGuid>48800d0d-e65a-4a82-9ea0-cadf2ac4371f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;AuthTemplate___StyledDiv6-sc-1req0pj-8 kPLZPU&quot;]/div[@class=&quot;AuthTemplate___StyledDiv7-sc-1req0pj-9 UEjqc&quot;]/div[@class=&quot;AuthPage___StyledDiv5-sc-8hlss4-18 kWXcso&quot;]/div[@class=&quot;AuthPage___StyledDiv7-sc-8hlss4-20 fSsHyV&quot;]/div[1]/form[1]/div[@class=&quot;RegisterForm___StyledDiv5-da6n5x-8 hPJWwU&quot;]/div[@class=&quot;Input___StyledDiv7-sc-1en4ex3-12 koNBaO&quot;]/div[@class=&quot;Input__StyledInput-sc-1en4ex3-3 cpMbPW&quot;]/input[@class=&quot;Input___StyledInput-sc-1en4ex3-14 ezAWtV&quot;]</value>
      <webElementGuid>9667cec1-2d90-4448-b5d1-6be12ab335e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='name']</value>
      <webElementGuid>7c335733-051b-46dd-adeb-72f35a77d3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div[2]/div/form/div/div/div/input</value>
      <webElementGuid>c0b40314-fe95-47d9-a871-c569b5afe72d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>375eeefe-7206-4101-a5e9-e87df0008757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'name']</value>
      <webElementGuid>257cd2ab-9706-40e3-9189-0b515b5ccb73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
