<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Antar barang melalui Kurir_fa fa-circle-o</name>
   <tag></tag>
   <elementGuidId>897c70bf-4bdb-49bc-8353-2d098eff8018</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='cart-form']/div/div[3]/div/div/div/div/div[2]/div[2]/label/i[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cart__dv__block.cart__dv--cod > div.cart__dv__content > label.cart__dv__list > i.fa.fa-circle-o</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>890e97c6-2d32-4731-92a0-926193a78f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-circle-o</value>
      <webElementGuid>ad8fd540-845c-432c-aa4f-3c12f0d264dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-form&quot;)/div[@class=&quot;cart&quot;]/div[@class=&quot;cart__action__container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;cart__action&quot;]/div[@class=&quot;form--cart&quot;]/div[@class=&quot;cart__dv__wrapper&quot;]/div[@class=&quot;cart__dv__block cart__dv--cod&quot;]/div[@class=&quot;cart__dv__content&quot;]/label[@class=&quot;cart__dv__list&quot;]/i[@class=&quot;fa fa-circle-o&quot;]</value>
      <webElementGuid>71e155b7-bfcf-45cb-be0b-b0a1bd4d9e3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cart-form']/div/div[3]/div/div/div/div/div[2]/div[2]/label/i[2]</value>
      <webElementGuid>ab64a74a-cfe1-46d9-ae59-7c8bd4569565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/label/i[2]</value>
      <webElementGuid>69103b82-3dc2-489f-b48d-8e48b3933342</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
