<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mengerti</name>
   <tag></tag>
   <elementGuidId>81561861-5ca7-4315-a29c-1cac7d31587b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-popover-panel-2']/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.SelectBranchButton___StyledDiv3-sc-1oov5eu-5.epIuzd > button.Button__StyledButton-sc-1l0qx1m-2.ieGcCN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bdebeaae-6174-4750-89f4-4f67c0d2a88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>931d98c5-57ad-45e5-9ab5-12265db71214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>20c0d4a6-a837-43b5-8b5e-08afb4f10be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-variant</name>
      <type>Main</type>
      <value>outlined</value>
      <webElementGuid>2b1fc8ad-a73b-4933-b18e-6b5a6ca52f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9cbdd3e5-3f58-4f43-b1a3-a12c4eee7516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-square</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1060463f-7cd8-47b4-8750-4f67a0b9b24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4bb3481a-7d4a-48b3-8889-d0bdc8a4fbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__StyledButton-sc-1l0qx1m-2 ieGcCN</value>
      <webElementGuid>a6ce788f-268f-4583-85e3-8400103c9f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mengerti</value>
      <webElementGuid>c3a19db0-c905-48d5-bc90-965d738fa241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-popover-panel-2&quot;)/div[@class=&quot;SelectBranchButton___StyledDiv2-sc-1oov5eu-4 kVtwDZ&quot;]/div[@class=&quot;SelectBranchButton___StyledDiv3-sc-1oov5eu-5 epIuzd&quot;]/button[@class=&quot;Button__StyledButton-sc-1l0qx1m-2 ieGcCN&quot;]</value>
      <webElementGuid>3a3f442d-3b74-4037-bdc3-22c2af78bb0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-popover-panel-2']/div/div[2]/button</value>
      <webElementGuid>aabf406d-aeab-4026-aa32-2f25602f7cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‚'])[1]/following::button[1]</value>
      <webElementGuid>c1fb0920-ab10-4f84-ba67-f2ae05bb1e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>954a6c5a-652b-4aa9-bb3e-ea16eede8318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Mengerti' or . = 'Mengerti')]</value>
      <webElementGuid>7dede0ff-ecf4-46ef-a43d-dc9a703a6e7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
