<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kategori_key</name>
   <tag></tag>
   <elementGuidId>f3c1fa43-4ac7-4b2b-9934-f2186b7cf18b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='key']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;key&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c571395c-eb74-44eb-a9be-79b20e6c0958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>key</value>
      <webElementGuid>cf29366a-7459-40f8-974d-3790530e7682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Xiaomi Gaming Monitor</value>
      <webElementGuid>8e077429-913b-4434-b8a4-826dc30918b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input___StyledInput-sc-1en4ex3-14 iBceOH</value>
      <webElementGuid>b456d612-c42c-4d0f-9380-b416d1ef1e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-sm Header___StyledMedia-y4d4ki-39 eRNBMj&quot;]/header[@class=&quot;Header___StyledHeader-y4d4ki-40 eCJwfa&quot;]/div[@class=&quot;Header___StyledDiv20-y4d4ki-41 iIUSWJ&quot;]/div[@class=&quot;Header___StyledDiv21-y4d4ki-42 fwlHyX&quot;]/div[@class=&quot;Header___StyledDiv24-y4d4ki-45 iotksB&quot;]/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-sm&quot;]/div[1]/form[1]/div[@class=&quot;SearchSection___StyledDiv-rs4tda-5 byResk&quot;]/div[@class=&quot;Input___StyledDiv7-sc-1en4ex3-12 koNBaO&quot;]/div[@class=&quot;Input__StyledInput-sc-1en4ex3-3 dnjqkY&quot;]/input[@class=&quot;Input___StyledInput-sc-1en4ex3-14 iBceOH&quot;]</value>
      <webElementGuid>158a5aa3-82d2-444b-95f5-440d32d0d3bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='key']</value>
      <webElementGuid>a90b00c0-a346-40a4-9909-65fe06231870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div[4]/header/div/div/div[2]/div[2]/div/form/div/div/div/input</value>
      <webElementGuid>3e18316a-cecb-4e8b-8769-3499336b78d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9f306463-0541-4ca8-8106-0eba347f25d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'key' and @placeholder = 'Xiaomi Gaming Monitor']</value>
      <webElementGuid>787b512d-e586-4e73-bde1-7481ff7da2a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
