<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login  Daftar</name>
   <tag></tag>
   <elementGuidId>eba823a7-d1ab-4e3a-8ce6-9a1082748384</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div[4]/header/div/div[3]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a896c37c-67e6-4633-984b-420fd4b586ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>88839f19-3978-4354-b9d8-32c31c512c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>medium</value>
      <webElementGuid>4597bc1c-b79f-43c8-b7c3-efed0896e60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-variant</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb0dd6f9-1fd5-4008-9628-dc44d229337b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>de9bff98-ea00-4f92-ae72-c9073b830b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-square</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aa8f6fec-9780-498c-ae39-0e0d21981099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb286560-2845-401d-a897-8a31cf97495e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__StyledButton-sc-1l0qx1m-2 ieGcCN</value>
      <webElementGuid>8fe15c42-3bb5-4622-92a9-91b3f80b4f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login / Daftar</value>
      <webElementGuid>c93e0b35-fd53-4177-80e6-5a2516a78ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-sm Header___StyledMedia-y4d4ki-39 eRNBMj&quot;]/header[@class=&quot;Header___StyledHeader-y4d4ki-40 eCJwfa&quot;]/div[@class=&quot;Header___StyledDiv20-y4d4ki-41 iIUSWJ&quot;]/div[@class=&quot;Header___StyledDiv26-y4d4ki-47 kEQDlx&quot;]/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-lg&quot;]/button[@class=&quot;Button__StyledButton-sc-1l0qx1m-2 ieGcCN&quot;]</value>
      <webElementGuid>c27a0555-4870-452f-bea9-506c5c0b5749</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div[4]/header/div/div[3]/div[2]/button</value>
      <webElementGuid>360dd032-bd41-4fa6-a30c-1801183b1ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Cart'])[1]/following::button[1]</value>
      <webElementGuid>936366b5-cd13-46da-9a48-b3e71ed85918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xiaomi Gaming Monitor'])[1]/following::button[2]</value>
      <webElementGuid>1cdb07d6-7e8b-4997-bea0-8c7aa67701ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::button[1]</value>
      <webElementGuid>3b279384-adf5-4add-aa35-d2a2ba4a7440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>701a4cb3-3ff6-4d83-8068-4f02123059ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Login / Daftar' or . = 'Login / Daftar')]</value>
      <webElementGuid>59d2d59e-0ab1-4ed8-8aeb-d359371bb80a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
