<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mengerti</name>
   <tag></tag>
   <elementGuidId>8db975f9-d2f6-4d95-9e93-92b48781982b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-popover-panel-2']/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.SelectBranchButton___StyledDiv3-sc-1oov5eu-5.epIuzd > button.Button__StyledButton-sc-1l0qx1m-2.ieGcCN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c09b6e2b-595a-40b4-80d1-d82d65bb3114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>c4e1418f-d85f-4b33-ae3d-6e45e67fafb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>578bc0fb-1695-4ebb-ab3a-33517766f512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-variant</name>
      <type>Main</type>
      <value>outlined</value>
      <webElementGuid>a8afa490-5e05-43e4-a349-ed107d8f9507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>483494be-ba94-4fe6-aa10-6d6a6b3526a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-square</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>acf122ff-3b33-47e8-9018-fb6221842747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3461468c-a59f-4f32-be81-5289b172b304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__StyledButton-sc-1l0qx1m-2 ieGcCN</value>
      <webElementGuid>a7d4db46-c680-459f-ba1c-77d401efe992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mengerti</value>
      <webElementGuid>fc87c1a9-25c6-47ac-9e03-5aaeace7f834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-popover-panel-2&quot;)/div[@class=&quot;SelectBranchButton___StyledDiv2-sc-1oov5eu-4 kVtwDZ&quot;]/div[@class=&quot;SelectBranchButton___StyledDiv3-sc-1oov5eu-5 epIuzd&quot;]/button[@class=&quot;Button__StyledButton-sc-1l0qx1m-2 ieGcCN&quot;]</value>
      <webElementGuid>c58755fa-1c79-4c8b-99f4-2ceffcedbf4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-popover-panel-2']/div/div[2]/button</value>
      <webElementGuid>26f4f62f-2947-43ae-868e-b0077df8695e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‚'])[1]/following::button[1]</value>
      <webElementGuid>9ea6a9fc-1da7-4025-b808-45667aed181d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>4d5a09d5-20ad-4d20-a98c-6d1344e4dd7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>d11b8bb3-057c-467c-bed7-5b6ea2db53cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Mengerti' or . = 'Mengerti')]</value>
      <webElementGuid>2b5b2f61-163b-43b1-a397-55d36f75b8ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
