<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_atau_username</name>
   <tag></tag>
   <elementGuidId>e20be598-1cb7-47ee-bbb1-3ff618fe3e03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;username&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a27a234-d13a-47d8-913a-586d951bfbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>4e8dd0af-bbe6-4df5-8bb9-660e3e083163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input___StyledInput-sc-1en4ex3-14 ezAWtV</value>
      <webElementGuid>04d7b04c-73bc-4bec-aabf-aacb48bcf2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-6&quot;)/div[@class=&quot;AuthService___StyledDiv-eztrj2-1 hEFEDD&quot;]/div[@class=&quot;AuthService___StyledDiv2-eztrj2-2 fUoFRe&quot;]/div[@class=&quot;Paper___StyledDiv-sc-1ow4efr-0 huGXsB AuthService___StyledPaper-eztrj2-3 byJlRI&quot;]/div[@class=&quot;LoginForm___StyledDiv-v7mguz-0 hcctiv&quot;]/form[1]/div[@class=&quot;LoginForm___StyledDiv6-v7mguz-9 bKmlEY&quot;]/div[@class=&quot;Input___StyledDiv7-sc-1en4ex3-12 koNBaO&quot;]/div[@class=&quot;Input__StyledInput-sc-1en4ex3-3 cpMbPW&quot;]/input[@class=&quot;Input___StyledInput-sc-1en4ex3-14 ezAWtV&quot;]</value>
      <webElementGuid>beaa21a6-bc84-43ce-aca3-184b3b6d9dbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>e040b7ae-dcef-4a8b-a87e-96bcd2731ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-6']/div[2]/div/div/div/form/div/div/div/input</value>
      <webElementGuid>ce0d6df2-b9e8-4ba0-b607-37d802a48030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/form/div/div/div/input</value>
      <webElementGuid>3c0f9292-5852-48f7-8174-d6fd0f712b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username']</value>
      <webElementGuid>822bb5ea-7787-4678-92c1-638ee5e67c14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
