<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Mengerti (1)</name>
   <tag></tag>
   <elementGuidId>df901919-7970-457a-b7ac-975b6330b2cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.SelectBranchButton___StyledDiv3-sc-1oov5eu-5.epIuzd > button.Button__StyledButton-sc-1l0qx1m-2.ieGcCN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-popover-panel-2']/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99faf16a-e95b-469b-a5e7-16504586cc8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>5d708f05-5d2e-47de-97c6-cfa904d1d9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>cc73d730-edce-4385-9dde-5267a76ae701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-variant</name>
      <type>Main</type>
      <value>outlined</value>
      <webElementGuid>a855bca8-d87b-494b-a873-7c9cb44f3fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>91889cf2-3226-4a79-9b51-7aaf2311ad13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-square</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4c02972b-d3df-4d11-bd68-6877de9099fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>de66f869-4bdb-4d4a-8d51-8752c0182019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__StyledButton-sc-1l0qx1m-2 ieGcCN</value>
      <webElementGuid>053a2d8f-aa50-4732-b490-ba91e191fb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mengerti</value>
      <webElementGuid>3ec81248-5ca4-486b-9a62-37410558558f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-popover-panel-2&quot;)/div[@class=&quot;SelectBranchButton___StyledDiv2-sc-1oov5eu-4 kVtwDZ&quot;]/div[@class=&quot;SelectBranchButton___StyledDiv3-sc-1oov5eu-5 epIuzd&quot;]/button[@class=&quot;Button__StyledButton-sc-1l0qx1m-2 ieGcCN&quot;]</value>
      <webElementGuid>ff2bd4bb-90be-4ccb-8dc4-0072ded08dd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-popover-panel-2']/div/div[2]/button</value>
      <webElementGuid>4d870183-49ca-4e6c-b38d-8f8cd2d78c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‚'])[1]/following::button[1]</value>
      <webElementGuid>ecc495df-ffed-4953-9343-317e2d7bb1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>16dd59e6-796a-45b4-b46f-ce2970469494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Mengerti' or . = 'Mengerti')]</value>
      <webElementGuid>5a1a5c7b-d563-4f0d-8102-b5277536989b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
