<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Xiaomi Gaming Monitor_Button__Styled_4d64f4</name>
   <tag></tag>
   <elementGuidId>0b182015-cddd-44c6-b157-558e908f54d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div[4]/header/div/div/div[2]/div[2]/div/form/div/div/div/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Button__StyledButton-sc-1l0qx1m-2.ieGcCN.SearchSection___StyledButton-rs4tda-1.cuHtqR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52a92910-ed02-4b55-8ef6-c91ed00977b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__StyledButton-sc-1l0qx1m-2 ieGcCN SearchSection___StyledButton-rs4tda-1 cuHtqR</value>
      <webElementGuid>d0618c46-0f06-492c-9b32-4ad7f3f420df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>02558184-00d1-496d-bdbe-b4548378e7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>55ce194d-e52e-4cd4-8384-902b57bbf5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-variant</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>333dd6f5-496d-4e06-91ae-a7fb89790091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e00b538e-9ba6-44d9-a540-9b46a4a7e13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-square</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cf3e6243-2a5a-4ab8-b1d2-4e5d18f4091d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c92a5e92-1e05-4b98-b5bd-d49ce94ac3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-sm Header___StyledMedia-y4d4ki-39 eRNBMj&quot;]/header[@class=&quot;Header___StyledHeader-y4d4ki-40 eCJwfa&quot;]/div[@class=&quot;Header___StyledDiv20-y4d4ki-41 iIUSWJ&quot;]/div[@class=&quot;Header___StyledDiv21-y4d4ki-42 fwlHyX&quot;]/div[@class=&quot;Header___StyledDiv24-y4d4ki-45 iotksB&quot;]/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-sm&quot;]/div[1]/form[1]/div[@class=&quot;SearchSection___StyledDiv-rs4tda-5 byResk&quot;]/div[@class=&quot;Input___StyledDiv7-sc-1en4ex3-12 koNBaO&quot;]/div[@class=&quot;Input__StyledInput-sc-1en4ex3-3 dnjqkY&quot;]/div[@class=&quot;Input___StyledDiv6-sc-1en4ex3-11 gxJYcX&quot;]/button[@class=&quot;Button__StyledButton-sc-1l0qx1m-2 ieGcCN SearchSection___StyledButton-rs4tda-1 cuHtqR&quot;]</value>
      <webElementGuid>4bdf15ba-bbb4-46a3-9bac-df3bea99f616</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div[4]/header/div/div/div[2]/div[2]/div/form/div/div/div/div[3]/button</value>
      <webElementGuid>870172e7-7548-41eb-8db0-1d464c3fbc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xiaomi Gaming Monitor'])[1]/following::button[1]</value>
      <webElementGuid>648b89a6-c203-491d-b7c6-a1038e5975f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::button[1]</value>
      <webElementGuid>1e98b6c4-3165-4018-a301-8de53556e0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian populer'])[1]/preceding::button[1]</value>
      <webElementGuid>b7bb29c1-6627-4a9a-8c43-f47a75a733d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Humidifier'])[1]/preceding::button[1]</value>
      <webElementGuid>1aecb3be-c12a-40eb-a4af-cc74eeff807b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>d133a0cf-d1d4-45f6-b546-396c0e6cd589</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
