<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kategori_key</name>
   <tag></tag>
   <elementGuidId>18c06fbc-b9a2-40b5-b66c-6355ceafb183</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='key']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;key&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bf50fb0-57ba-49ee-bfbb-420e2719e0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>key</value>
      <webElementGuid>c575fc0c-0bd9-45a5-99de-5b73a11a3aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Xiaomi Gaming Monitor</value>
      <webElementGuid>d64c1068-8e03-4de3-a67a-0d5ae6033ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input___StyledInput-sc-1en4ex3-14 iBceOH</value>
      <webElementGuid>84af7d8d-6a69-49c7-93d1-f517b4572908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-sm Header___StyledMedia-y4d4ki-39 eRNBMj&quot;]/header[@class=&quot;Header___StyledHeader-y4d4ki-40 eCJwfa&quot;]/div[@class=&quot;Header___StyledDiv20-y4d4ki-41 iIUSWJ&quot;]/div[@class=&quot;Header___StyledDiv21-y4d4ki-42 fwlHyX&quot;]/div[@class=&quot;Header___StyledDiv24-y4d4ki-45 iotksB&quot;]/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-sm&quot;]/div[1]/form[1]/div[@class=&quot;SearchSection___StyledDiv-rs4tda-5 byResk&quot;]/div[@class=&quot;Input___StyledDiv7-sc-1en4ex3-12 koNBaO&quot;]/div[@class=&quot;Input__StyledInput-sc-1en4ex3-3 dnjqkY&quot;]/input[@class=&quot;Input___StyledInput-sc-1en4ex3-14 iBceOH&quot;]</value>
      <webElementGuid>1e86345b-7929-4bd2-b527-de70c5a3a550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec1044ce-8034-477d-bdfd-b2b13c598644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>key</value>
      <webElementGuid>f2212eab-e305-49dd-8b6e-5723dc317997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Xiaomi Gaming Monitor</value>
      <webElementGuid>1b0a70a2-8d74-4551-b8b4-cdea6e43d586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input___StyledInput-sc-1en4ex3-14 iBceOH</value>
      <webElementGuid>58c37533-a8e1-4c18-885e-a5a513c26a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-sm Header___StyledMedia-y4d4ki-39 eRNBMj&quot;]/header[@class=&quot;Header___StyledHeader-y4d4ki-40 eCJwfa&quot;]/div[@class=&quot;Header___StyledDiv20-y4d4ki-41 iIUSWJ&quot;]/div[@class=&quot;Header___StyledDiv21-y4d4ki-42 fwlHyX&quot;]/div[@class=&quot;Header___StyledDiv24-y4d4ki-45 iotksB&quot;]/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-sm&quot;]/div[1]/form[1]/div[@class=&quot;SearchSection___StyledDiv-rs4tda-5 byResk&quot;]/div[@class=&quot;Input___StyledDiv7-sc-1en4ex3-12 koNBaO&quot;]/div[@class=&quot;Input__StyledInput-sc-1en4ex3-3 dnjqkY&quot;]/input[@class=&quot;Input___StyledInput-sc-1en4ex3-14 iBceOH&quot;]</value>
      <webElementGuid>bd7a2664-63f8-4494-9621-f5271298f0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5090edee-fa69-436d-abb2-3bb0a04e5bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>key</value>
      <webElementGuid>76752b0e-3cff-41c5-a4f6-716690e8760e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Xiaomi Gaming Monitor</value>
      <webElementGuid>ff07a64f-aaa0-4641-b89f-9ebdf0f8641c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input___StyledInput-sc-1en4ex3-14 iBceOH</value>
      <webElementGuid>63084f62-f808-4083-9114-82b25f856a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-sm Header___StyledMedia-y4d4ki-39 eRNBMj&quot;]/header[@class=&quot;Header___StyledHeader-y4d4ki-40 eCJwfa&quot;]/div[@class=&quot;Header___StyledDiv20-y4d4ki-41 iIUSWJ&quot;]/div[@class=&quot;Header___StyledDiv21-y4d4ki-42 fwlHyX&quot;]/div[@class=&quot;Header___StyledDiv24-y4d4ki-45 iotksB&quot;]/div[@class=&quot;fresnel-container fresnel-greaterThanOrEqual-sm&quot;]/div[1]/form[1]/div[@class=&quot;SearchSection___StyledDiv-rs4tda-5 byResk&quot;]/div[@class=&quot;Input___StyledDiv7-sc-1en4ex3-12 koNBaO&quot;]/div[@class=&quot;Input__StyledInput-sc-1en4ex3-3 dnjqkY&quot;]/input[@class=&quot;Input___StyledInput-sc-1en4ex3-14 iBceOH&quot;]</value>
      <webElementGuid>edea4373-a49a-445a-bfa1-d8c643d07fe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='key']</value>
      <webElementGuid>8afdc93a-baad-4160-b147-b7cf7c417f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div[4]/header/div/div/div[2]/div[2]/div/form/div/div/div/input</value>
      <webElementGuid>d2a83849-5158-4783-8641-a998381ebb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e497ab43-ca67-4df7-ad3a-34971329e581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'key' and @placeholder = 'Xiaomi Gaming Monitor']</value>
      <webElementGuid>e4c4a891-e94f-4be4-8edf-6573dd93ca74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
