<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_atau_username (1)</name>
   <tag></tag>
   <elementGuidId>89a5ed27-3075-4f1f-9f79-315507167646</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;username&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48f381a1-23aa-42ca-8ae4-d3b1cf30fce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>c60132c0-3af5-4646-83b4-912ddf9691dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input___StyledInput-sc-1en4ex3-14 ezAWtV</value>
      <webElementGuid>8a6d18df-9e27-49ba-97e2-784480c726a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-6&quot;)/div[@class=&quot;AuthService___StyledDiv-eztrj2-1 hEFEDD&quot;]/div[@class=&quot;AuthService___StyledDiv2-eztrj2-2 fUoFRe&quot;]/div[@class=&quot;Paper___StyledDiv-sc-1ow4efr-0 huGXsB AuthService___StyledPaper-eztrj2-3 byJlRI&quot;]/div[@class=&quot;LoginForm___StyledDiv-v7mguz-0 hcctiv&quot;]/form[1]/div[@class=&quot;LoginForm___StyledDiv6-v7mguz-9 bKmlEY&quot;]/div[@class=&quot;Input___StyledDiv7-sc-1en4ex3-12 koNBaO&quot;]/div[@class=&quot;Input__StyledInput-sc-1en4ex3-3 cpMbPW&quot;]/input[@class=&quot;Input___StyledInput-sc-1en4ex3-14 ezAWtV&quot;]</value>
      <webElementGuid>385c6c44-088f-46fd-8f26-1afb27d57c67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='username']</value>
      <webElementGuid>d83057ac-dbfc-4afa-b707-6861176dffd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-6']/div[2]/div/div/div/form/div/div/div/input</value>
      <webElementGuid>42dd6f79-02e8-4700-a697-b7de774bf9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/form/div/div/div/input</value>
      <webElementGuid>e49cbf0d-feb0-4dcc-81db-f42bcb424681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username']</value>
      <webElementGuid>158a7cd2-065a-4424-bcd6-ab5a19248611</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
