<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SKMEI Jam Tangan Analog Chrono Pria Stain_46b265</name>
   <tag></tag>
   <elementGuidId>08d08042-9e15-44be-98be-a6708e070997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='EMWSFNBK'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>080e935a-3bc9-445b-b4cb-50f3e4d7681b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.jakartanotebook.com/skmei-jam-tangan-analog-chrono-pria-stainless-steel-strap-1515-black</value>
      <webElementGuid>df866082-b960-4f92-8e29-128e6049e339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SKMEI Jam Tangan Analog Chrono Pria Stainless Steel Strap - 1515 - Black</value>
      <webElementGuid>05d87cfe-248d-4ab7-8574-e33c69b58257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-list__title</value>
      <webElementGuid>74ea5dd6-eec3-4697-8e3b-8de0a15feb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SKMEI Jam Tangan Analog Chrono Pria Stainless Steel Strap - 1515 - Black</value>
      <webElementGuid>afc32582-0fae-400f-ae51-1fca2bd5fb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy no-touch history rgba multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent&quot;]/body[@class=&quot;page-body&quot;]/div[3]/div[@class=&quot;mainContent&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;product-list-wrapper&quot;]/div[@class=&quot;product-list&quot;]/div[@class=&quot;product-list__header&quot;]/a[@class=&quot;product-list__title&quot;]</value>
      <webElementGuid>dd3699ab-e841-4c11-ab64-6fd6ee3cc4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63b4d841-b211-4634-a250-8aaf7fe21d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.jakartanotebook.com/skmei-jam-tangan-analog-chrono-pria-stainless-steel-strap-1515-black</value>
      <webElementGuid>4ee92395-f0cd-437d-857c-aaeea61ef2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>SKMEI Jam Tangan Analog Chrono Pria Stainless Steel Strap - 1515 - Black</value>
      <webElementGuid>c4e3a962-763e-4236-b243-466ce99d7b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-list__title</value>
      <webElementGuid>9a0b4218-5603-4b9c-8c33-1410e5b6eb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SKMEI Jam Tangan Analog Chrono Pria Stainless Steel Strap - 1515 - Black</value>
      <webElementGuid>c20bae8f-a78b-4362-9b1f-11b64cd6b40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy no-touch history rgba multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent&quot;]/body[@class=&quot;page-body&quot;]/div[3]/div[@class=&quot;mainContent&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;product-list-wrapper&quot;]/div[@class=&quot;product-list&quot;]/div[@class=&quot;product-list__header&quot;]/a[@class=&quot;product-list__title&quot;]</value>
      <webElementGuid>eb1cf0dc-7f0c-4a05-a33c-1ef38b6c61a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMWSFNBK'])[1]/following::a[1]</value>
      <webElementGuid>532dc845-97b6-4d6c-83a6-d6d88aaf8a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak tersedia di lokasi lain.'])[1]/following::a[1]</value>
      <webElementGuid>87a2cdbb-50a8-48ba-ae87-7ab1a319fabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='['])[2]/preceding::a[2]</value>
      <webElementGuid>1bf17fce-b2f5-4a2f-9616-68f2e2d36261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.jakartanotebook.com/skmei-jam-tangan-analog-chrono-pria-stainless-steel-strap-1515-black')]</value>
      <webElementGuid>94fc6416-57da-4afc-8da6-2c71e76afd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>c5c72bd2-10e7-48ca-b649-0ca72d64d02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.jakartanotebook.com/skmei-jam-tangan-analog-chrono-pria-stainless-steel-strap-1515-black' and @title = 'SKMEI Jam Tangan Analog Chrono Pria Stainless Steel Strap - 1515 - Black' and (text() = 'SKMEI Jam Tangan Analog Chrono Pria Stainless Steel Strap - 1515 - Black' or . = 'SKMEI Jam Tangan Analog Chrono Pria Stainless Steel Strap - 1515 - Black')]</value>
      <webElementGuid>eac49cca-918a-4c77-86b4-57814d856b60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
