<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Daftar</name>
   <tag></tag>
   <elementGuidId>734a1637-4cc3-4ce1-b266-a221f6836f01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div[2]/div/form/div[6]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Button__StyledButton-sc-1l0qx1m-2.ieGcCN.RegisterForm___StyledJaknotButton-da6n5x-15.hifTWh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cab20ed9-33c1-4071-8088-03f8e2177624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__StyledButton-sc-1l0qx1m-2 ieGcCN RegisterForm___StyledJaknotButton-da6n5x-15 hifTWh</value>
      <webElementGuid>711b0cbd-d66c-40f4-88af-46e3ae8c1829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>007ce2a8-dd43-43eb-8e6b-c4f2d97c690d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>large</value>
      <webElementGuid>beb2b7c6-8f57-4de0-af9a-8d493b5b05f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-variant</name>
      <type>Main</type>
      <value>contained</value>
      <webElementGuid>d7f2da49-def6-493d-a948-86368739bb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1507fe6-82e9-4121-bde5-964670cfb683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-square</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b4243c52-b6c5-4115-baa1-312ba32f18ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a696228a-2f72-4617-a027-044630e34f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>3600cee8-913e-49f1-a619-f1ac6eb612d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;AuthTemplate___StyledDiv6-sc-1req0pj-8 kPLZPU&quot;]/div[@class=&quot;AuthTemplate___StyledDiv7-sc-1req0pj-9 UEjqc&quot;]/div[@class=&quot;AuthPage___StyledDiv5-sc-8hlss4-18 kWXcso&quot;]/div[@class=&quot;AuthPage___StyledDiv7-sc-8hlss4-20 fSsHyV&quot;]/div[1]/form[1]/div[@class=&quot;RegisterForm___StyledDiv10-da6n5x-14 bdyPwN&quot;]/button[@class=&quot;Button__StyledButton-sc-1l0qx1m-2 ieGcCN RegisterForm___StyledJaknotButton-da6n5x-15 hifTWh&quot;]</value>
      <webElementGuid>63003de2-3ef9-43b2-adbf-2bbf015bedec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div[2]/div/form/div[6]/button</value>
      <webElementGuid>b18321ce-dec6-40a0-9f45-73d2a2e3bc72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat dan Ketentuan'])[1]/following::button[1]</value>
      <webElementGuid>38a7d449-5867-4697-a33f-bf3dab5fd2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[1]/preceding::button[1]</value>
      <webElementGuid>72d048c8-cc1d-4bbe-8925-13c89c5845f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>cc14d182-51d2-4575-8eea-a0e76fb38e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>f5f91570-4037-4921-aa12-ef4b753eaee5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
